### PR TITLE
main: Switch from flag to pflag

### PR DESCRIPTION
**Pull request by bgilbert**
`pflag` is more flexible.  It allows us to add short options, which we do here.  It also supports hidden options, which is useful for fixing #69.

This is a backward-incompatible change.  `flag` accepts e.g. both `-strict` and `--strict`, but documents `-strict` in the help text.  `pflag` documents `--strict` and accepts only `--strict`.

This will break people's scripts.  However, we're technically still in 0.x-land.  If we want to switch to a more conventional parser with double-dash long arguments, it's only going to get harder from here.

Thoughts?

### CODE REVIEW

**Comment by lucab** [comment]
Breaking is not nice, but I'm in favor of doing this cleanup. Thus, better now than later.

I'm not exactly buying the 0.x argument, but I think at this point most of `fcct` users are still in the initial manual/exploration phase OR pinning the container version. So the blast radius of this PR should be not too big.

**Comment by ashcrow** [comment]
> Breaking is not nice, but I'm in favor of doing this cleanup. Thus, better now than later.

I agree :+1:

**Comment by ashcrow** [comment]
4 :+1:'s ... merging :smile:

**Comment by lucab** [comment]
@jlebon that's https://github.com/coreos/fedora-coreos-docs/pull/35.

**Comment by dustymabe** [comment]
since this merged should we consider a larger version bump for our next release?

**Comment by bgilbert** [comment]
@dustymabe SemVer says anything goes for 0.x versions.  We'll call out the breaking change in the release notes.

**Pull request merged**
