### PR TITLE
base/v0_2_exp: translate httpHeaders fields

### PR DESCRIPTION
**Pull request by bgilbert**

### CODE REVIEW

**Comment by lucab** [comment]
[Please bear with me if the following is a dumb question]
Don't we have to wait for `3.1.0` Ignition schema in order to wire this here? Otherwise, won't this generate a `-experimental` version which eventually won't be accepted anymore by Ignition?

**Comment by bgilbert** [comment]
FCCs are versioned.  Base `0.2-exp` is only used by FCCL `1.1.0-experimental`, which targets Ignition spec `3.1.0-experimental`.  FCCL `1.0.0` targets spec `3.0.0` and isn't affected by this PR.

**Comment by lucab** [comment]
Yes, I'm only looking at the `1.1.0-experimental` -> `3.1.0-experimental` edge, which produces an output which is valid today but it won't be at an arbitrary point in the future.

But I take that this is already the case today, so overall it is not deemed a concern, right?
Other than this silly doubt of mine (about an already existing behavior), the PR looks fine.

**Comment by bgilbert** [comment]
> Yes, I'm only looking at the `1.1.0-experimental` -> `3.1.0-experimental` edge, which produces an output which is valid today but it won't be at an arbitrary point in the future.

Yup, that's already the case, and is by design.

**Comment by lucab** [comment]
LGTM, thanks for the concise/explicit walkthrough!

**Pull request merged**
