### PR TITLE
[docs]: Add CA bundle information

### LINKED ISSUE #103: Update docs for CA bundles support
This involves updating the description for the `source` field for both the config specs i.e. `v1.0.0-exp` and `v1.1.0-experimental`.

### PR DESCRIPTION
**Pull request by sohankunkerkar**
Fixes #103 (not mergeable until https://github.com/coreos/fcct/pull/102 gets merged)

### CODE REVIEW

**Comment by bgilbert** [comment]
#102 merged.  Please rebase, and change your commit message to be consistent with the style of other commits in the repo.

**Comment by sohankunkerkar** [comment]
Done!

**Comment by ashcrow** [comment]
https://github.com/coreos/fcct/pull/102 has merged.

**Comment by bgilbert** [comment]
Followup in #105.

**Pull request merged**
